### ISSUE TITLE
Exclude unnecessery directories before publish to npm

### ISSUE THREAD

**Issue by cuongdd2** [GoodgameStudios/RobotlegsJS#16]
In npm packages of `robotlegs, robotlegs-pixi, robotlegs-singalcommandmap` there are`.idea` and `node_modules` directories. 
It causes to `Cannot find type definition file for 'chai'.` error and increase npm packges size.
Please exclude them before publish to npm.

Thanks.

**Comment by endel** [comment]
Hi @cuongdd2, thanks for reporting. We're investigating this problem with definition of `chai`. For now, you can simply install its type definitions to get rid of the error (`npm install --save @types/chai`)

**Comment by tiagoschenkel** [comment]
Hi @cuongdd2, I think now the latest version of all packages mentioned by you are not including anymore the `.idea` folder and other unnecessary files.

Could you please create a empty project, import all packages and check if we are only publishing the necessary source code?

`mkdir test`
`cd test`
`npm init`
`npm install signals.js --save`
`npm install robotlegs --save`
`npm install robotlegs-macrobot --save`
`npm install robotlegs-signalcommandmap --save`
`npm install robotlegs-pixi --save`

**Comment by endel** [comment]
Using latest TypeScript version fixes this problem with `"chai"` reference being added. Currently fixed only on [SignalsJS](https://github.com/GoodgameStudios/SignalsJS/commit/d0c10a6652b71fbc4b66db2111845bd3459e9f19).

**Comment by tiagoschenkel** [comment]
Problem solved on all of our repositories:
- signals.js
- robotlegs
- robotlegs-macrobot
- robotlegs-signalcommandmap
- robotlegs-pixi
